FROM docker.io/library/golang:1.26

RUN go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.12.2
RUN go install github.com/mrtazz/checkmake/cmd/checkmake@0.2.2

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    shellcheck \
    nodejs \
    npm \
    make \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --break-system-packages yamllint==1.37.0
RUN npm install -g markdownlint-cli2@0.20.0

WORKDIR /src
